/** Mirror of ecosystem/framework/docs/consumer-pins.json — embedded for generated apps. */
export const PIN_OVERRIDES: Record<string, string> = {
  '@illumiarq/adapters': '1.2.0',
  '@illumiarq/auth': '1.1.5',
  '@illumiarq/build': '1.1.5',
  '@illumiarq/cache': '1.1.5',
  '@illumiarq/context': '1.1.5',
  '@illumiarq/contracts': '1.2.0',
  '@illumiarq/core': '1.1.6',
  '@illumiarq/database': '1.1.5',
  '@illumiarq/filesystem': '0.1.1',
  '@illumiarq/http': '1.1.5',
  '@illumiarq/key-value-storage': '0.1.1',
  '@illumiarq/lumis': '1.3.3',
  '@illumiarq/migrations': '1.1.5',
  '@illumiarq/modules': '1.1.5',
  '@illumiarq/query': '1.1.5',
  '@illumiarq/runtime': '1.2.0',
  '@illumiarq/security': '1.1.5',
  '@illumiarq/testing': '1.2.0',
  '@illumiarq/veil': '1.0.6',
  '@lumiarq/framework': '1.0.6',
  '@lumiarq/lumis': '1.2.14',
  '@lumiarq/agent': '1.1.1',
  '@lumiarq/pack-lumiarq': '1.0.1',
};
