import { writeFileSync, mkdirSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { resolve } from 'node:path';
import { arcDir, arcServer } from './paths.js';

/**
 * The ESM source that will become .arc/.server.mjs.
 *
 * The app bundle (./node/app.js) stays external — its path is preserved
 * as-is in the output so the relative import resolves correctly at runtime
 * from inside .arc/.
 *
 * @illumiarq/adapters/node is BUNDLED by esbuild so the wrapper is
 * self-contained regardless of pnpm hoisting.
 */
function wrapperSource(port: number): string {
  return [
    `import appPromise from './node/app.js';`,
    `import { startNodeServer } from '@illumiarq/adapters/node';`,
    `const app = await appPromise;`,
    `await startNodeServer(app.router, { port: ${port} });`,
    '',
  ].join('\n');
}

/**
 * Writes `.arc/.server.mjs` — a self-contained Node ESM bootstrap that
 * imports the built app bundle and starts the Node HTTP adapter.
 *
 * esbuild bundles `@illumiarq/adapters/node` inline so the wrapper needs no
 * extra dependencies at runtime. Falls back to writing plain ESM (bare
 * specifier) if esbuild is unavailable.
 *
 * @returns Absolute path to the written file.
 */
export function writeServerWrapper(port: number, cwd: string): string {
  const dir = arcDir(cwd);
  const wrapperPath = arcServer(cwd);

  mkdirSync(dir, { recursive: true });

  // Try to bundle @illumiarq/adapters/node inline via esbuild --stdin
  const result = spawnSync(
    'node_modules/.bin/esbuild',
    [
      '--bundle',
      '--platform=node',
      '--target=node20',
      '--format=esm',
      `--outfile=${wrapperPath}`,
      '--external:./node/app.js',
      // --sourcefile sets the virtual file path for stdin,
      // which tells esbuild to resolve imports relative to cwd.
      `--sourcefile=${resolve(cwd, 'stdin-entry.js')}`,
      '--log-level=error',
    ],
    {
      cwd,
      input: wrapperSource(port),
      encoding: 'utf8',
      stdio: ['pipe', 'pipe', 'pipe'],
    },
  );

  if (result.status !== 0) {
    // esbuild unavailable — write plain ESM; runtime relies on
    // @illumiarq/adapters being reachable via node_modules at cwd.
    writeFileSync(
      wrapperPath,
      `// Auto-generated by @illumiarq/lumis — do not edit.\n${wrapperSource(port)}`,
      'utf8',
    );
  }

  return wrapperPath;
}
