import { existsSync, mkdirSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';

import { ui, writeError, writeLine } from '../../console.js';
import { runBridge } from './command-runtime.js';

export function cacheRoutes(cwd = process.cwd()): number {
  const routesRoot = join(cwd, 'src', 'modules');
  if (!existsSync(routesRoot)) {
    writeError(ui.fail('No src/modules directory found.'));
    return 1;
  }

  const discovered: string[] = [];
  const stack = [routesRoot];
  while (stack.length > 0) {
    const current = stack.pop();
    if (!current) continue;

    for (const entry of readdirSync(current, { withFileTypes: true })) {
      const fullPath = join(current, entry.name);
      if (entry.isDirectory()) {
        stack.push(fullPath);
        continue;
      }
      if (/\/http\/routes\/.+\.(ts|js)$/.test(fullPath)) {
        discovered.push(fullPath);
      }
    }
  }

  discovered.sort((left, right) => left.localeCompare(right));

  const loaderPath = join(cwd, 'storage', 'framework', 'cache', 'routes.loader.ts');
  mkdirSync(dirname(loaderPath), { recursive: true });
  const importLines = discovered.map((filePath) => {
    const relativeImport = relative(
      join(cwd, 'storage', 'framework', 'cache'),
      filePath,
    ).replaceAll('\\', '/');
    return `import '${relativeImport}'`;
  });

  const content = [
    '// storage/framework/cache/routes.loader.ts',
    '// Auto-generated by `lumis route:cache` - do not edit manually.',
    '// Commit this file; re-run `lumis route:cache` whenever routes change.',
    '',
    ...importLines.map((line) => `${line};`),
    '',
  ].join('\n');

  writeFileSync(loaderPath, content, 'utf8');

  writeLine();
  writeLine(ui.section('Route Cache'));
  writeLine(`  ${ui.ok(`Cached ${discovered.length} route files`)}`);
  writeLine(`  ${ui.bullet(relative(cwd, loaderPath))}`);
  writeLine();
  return 0;
}

export function clearRouteCache(cwd = process.cwd()): number {
  const loaderPath = join(cwd, 'storage', 'framework', 'cache', 'routes.loader.ts');
  if (existsSync(loaderPath)) {
    rmSync(loaderPath, { force: true });
  }

  writeLine();
  writeLine(ui.section('Route Clear'));
  writeLine(`  ${ui.ok(`Removed ${relative(cwd, loaderPath)}`)}`);
  writeLine();
  return 0;
}

export function listRoutes(cwd = process.cwd()): number {
  const result = runBridge(['route:list', cwd], cwd);
  if (result.status !== 0) {
    writeError(ui.fail(result.stderr.trim() || 'Route listing failed.'));
    return result.status;
  }

  const parsed = JSON.parse(result.stdout) as {
    routes: Array<{
      method: string;
      path: string;
      name: string;
      render: string;
      middleware: string[];
    }>;
  };

  writeLine();
  writeLine(ui.section(`Routes (${parsed.routes.length})`));
  for (const route of parsed.routes) {
    const meta = [route.name || '-', route.render || '-', route.middleware.join(', ') || '-'].join(
      ' · ',
    );
    writeLine(`  ${ui.cyan(route.method.padEnd(6, ' '))} ${route.path} ${ui.dim(meta)}`);
  }
  writeLine();
  return 0;
}

export function checkRoutes(cwd = process.cwd()): number {
  const result = runBridge(['route:check', cwd], cwd);
  if (result.status !== 0) {
    writeError(ui.fail(result.stderr.trim() || 'Route check failed.'));
    return result.status;
  }

  const parsed = JSON.parse(result.stdout) as { routes: Array<unknown> };
  writeLine();
  writeLine(ui.section('Route Check'));
  writeLine(`  ${ui.ok(`${parsed.routes.length} routes validated`)}`);
  writeLine();
  return 0;
}
