export interface BffScaffoldOptions {
  /**
   * The package name to use in the scaffold.
   * Used in import statements.
   */
  packageName?: string;
  /**
   * Whether to include example request context bootstrap code.
   * Default: true.
   */
  includeContext?: boolean;
}

const DEFAULT_BFF_PORT = 4000;
const DEFAULT_MAX_PORT_ATTEMPTS = 50;

function createContextLines(): string[] {
  return [
    `// Wrap every request in a request context`,
    `app.use('*', async (c, next) => {`,
    `  const ctx = createRequestContext({ headers: Object.fromEntries(c.req.raw.headers) });`,
    `  await runWithContext(ctx, next);`,
    `});`,
    ``,
  ];
}

function createPortFallbackLines(): string[] {
  return [
    `const maxPortAttempts = Number.parseInt(process.env['LUMIARQ_MAX_PORT_ATTEMPTS'] ?? '${DEFAULT_MAX_PORT_ATTEMPTS}', 10);`,
    `startNodeServer(app, {`,
    `  port: Number(process.env['PORT'] ?? ${DEFAULT_BFF_PORT}),`,
    `  autoPortFallback: process.env['LUMIARQ_AUTO_PORT_FALLBACK'] !== 'false',`,
    `  maxPortAttempts: Number.isFinite(maxPortAttempts) && maxPortAttempts > 0 ? maxPortAttempts : ${DEFAULT_MAX_PORT_ATTEMPTS},`,
    `});`,
  ];
}

/**
 * Generates a minimal Backend-For-Frontend (BFF) entry point scaffold.
 *
 * The scaffold is a TypeScript string you can write to disk during a build step.
 * It wires up the Hono app with the LumiARQ node adapter and request context.
 *
 * @param options - Scaffold customisation options
 * @returns       - TypeScript source string for the BFF entry point
 */
export function generateBffScaffold(options: BffScaffoldOptions = {}): string {
  const { packageName = 'your-app', includeContext = true } = options;

  return [
    `/**`,
    ` * BFF Entry Point — generated by LumiARQ`,
    ` * Package: ${packageName}`,
    ` */`,
    `import { Hono } from 'hono';`,
    `import { startNodeServer } from '@velo/adapters/node';`,
    ...(includeContext
      ? [`import { runWithContext, createRequestContext } from '@velo/runtime';`]
      : []),
    ``,
    `const app = new Hono();`,
    ``,
    ...(includeContext ? createContextLines() : []),
    `// TODO: Register your routes here`,
    `// app.get('/', (c) => c.html('<h1>Hello LumiARQ</h1>'));`,
    ``,
    ...createPortFallbackLines(),
  ].join('\n');
}
